/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Scan a fabric surface, optionally cross-checked against care-label text.
         *
         *     ``label_text`` is a stop-gap: OCR currently runs on-device in the app and
         *     posts its text here. When the server-side OCR backend lands it will accept a
         *     ``label_image`` upload instead.
         */
        post: operations["scan_api_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_scan_api_v1_scan_post */
        Body_scan_api_v1_scan_post: {
            /** Label Text */
            label_text?: string | null;
            /** Surface Image */
            surface_image: string;
        };
        /** CaptureQuality */
        CaptureQuality: {
            /** Blur */
            blur?: number | null;
            /** Exposure */
            exposure?: string | null;
            /** Framing */
            framing?: string | null;
        };
        /**
         * CompositionSource
         * @enum {string}
         */
        CompositionSource: "care_label" | "purchase_order";
        /** FiberComponent */
        FiberComponent: {
            /** Name */
            name: string;
            /** Pct */
            pct: number;
        };
        /** FlagModel */
        FlagModel: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadPrediction */
        HeadPrediction: {
            /** Confidence */
            confidence: number;
            /** Label */
            label: string;
            /**
             * Topk
             * @default []
             */
            topk: [
                string,
                number
            ][];
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "PASS" | "FLAG" | "INSUFFICIENT_EVIDENCE";
        /** ScanResult */
        ScanResult: {
            /** @default {} */
            capture_quality: components["schemas"]["CaptureQuality"];
            fibre_family?: components["schemas"]["HeadPrediction"] | null;
            /**
             * Flags
             * @default []
             */
            flags: components["schemas"]["FlagModel"][];
            /** Kb Version */
            kb_version: string;
            /** Model Version */
            model_version: string;
            /** Scan Id */
            scan_id: string;
            /**
             * @default {
             *       "fibers": []
             *     }
             */
            stated_composition: components["schemas"]["StatedComposition"];
            structure?: components["schemas"]["HeadPrediction"] | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            treatment?: components["schemas"]["HeadPrediction"] | null;
            verdict: components["schemas"]["Outcome"];
        };
        /** StatedComposition */
        StatedComposition: {
            /**
             * Fibers
             * @default []
             */
            fibers: components["schemas"]["FiberComponent"][];
            /** Ocr Confidence */
            ocr_confidence?: number | null;
            source?: components["schemas"]["CompositionSource"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scan_api_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_api_v1_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
